---
name: Build and test

on:
  push:
    branches:
      - main
      - master
    tags:
      - "**"
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: "0 1 * * *"

permissions: read-all

jobs:
  build-and-test-bounded-doubles:
    uses: DepTyCheck/idris2-actions/.github/workflows/build-and-test.yml@v1
    with:
      ipkg_path: bounded-doubles.ipkg

  build-and-test-hedgehog-generators:
    uses: DepTyCheck/idris2-actions/.github/workflows/build-and-test.yml@v1
    with:
      ipkg_path: hedgehog-generators.ipkg
